# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ci-msvc

on:
  push:
    paths:
      - "**"
      - "!android/**"
      - "!docs/**"
      - "!**Makefile**"
      - "!ios/**"
      - "!macosx/**"
      - "!AUTHORS"
      - "!ChangeLog"
      - "!COPYING"
      - "!FAQ"
      - "!INSTALL"
      - "!NEWS"
      - "!**README**"
      - "!**.ico"
      - "!**.md"
      - "!**.png"
      - "!**.txt"
      - "!.clang*"
      - "!.gitignore"
      - "!.gitattributes"
      - "!.github/workflows/*"
      - ".github/workflows/ci-msvc.yml"
  pull_request:
    paths:
      - "**"
      - "!android/**"
      - "!docs/**"
      - "!**Makefile**"
      - "!ios/**"
      - "!macosx/**"
      - "!AUTHORS"
      - "!ChangeLog"
      - "!COPYING"
      - "!FAQ"
      - "!INSTALL"
      - "!NEWS"
      - "!**README**"
      - "!**.ico"
      - "!**.md"
      - "!**.png"
      - "!**.txt"
      - "!.clang*"
      - "!.gitignore"
      - "!.gitattributes"
      - "!.github/workflows/*"
      - ".github/workflows/ci-msvc.yml"
  
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: msvcstuff\vs2019

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

  #platform
  BUILD_PLATFORM: x64

  BUILD_PROJECTS: Exult

permissions:
  contents: read

jobs:
  ci-msvc:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          echo `ls`
  notify:
    name: Exult-CI (IRC & Discord notification)
    runs-on: ubuntu-latest
    continue-on-error: true
    needs:
      - ci-msvc
    steps:
      - name: Discord success notification
        uses: tsickert/discord-webhook@v6.0.0
        continue-on-error: true
        if: needs.ci-msvc.result == 'success'
        with:
          webhook-url: ${{ secrets.WEBHOOK }}
          content: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          username: github-actions
          avatar-url: "https://cdn.discordapp.com/avatars/999680196040982618/df91181b3f1cf0ef1592fbe18e0962d7.webp"
          embed-footer-text: ${{ github.event.head_commit.message }}
          embed-title: 'The MSVC build succeeded.'
          embed-color: 65280
          embed-author-name: ${{ github.event.head_commit.author.username }}
          #embed-author-url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          #embed-author-icon-url: ${{ github.event.pull_request.user.avatar_url }}
          #embed-description: ${{ github.event.pull_request.body }}
          embed-url: ${{ github.event.head_commit.url }}
          embed-timestamp: ${{ github.event.head_commit.timestamp }}
      - name: Discord success notification
        uses: rjstone/discord-webhook-notify@master
        continue-on-error: true
        with:
          severity: info
          username: github-actions
          webhookUrl: ${{ secrets.WEBHOOK }}
          text: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          #title: 'The macOS build succeeded.' 
      - name: Discord failure notification
        uses: tsickert/discord-webhook@v6.0.0
        continue-on-error: true
        if: needs.ci-msvc.result != 'success'
        with:
          username: github-actions
          webhook-url: ${{ secrets.WEBHOOK }}
          embed-footer-text: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          embed-title: 'The MSVC build failed.'
          embed-color: 16711680
          embed-author-name: ${{ github.event.pull_request.user.login }}
          embed-author-url: ${{ github.event.pull_request.user.html_url }}
          embed-author-icon-url: ${{ github.event.pull_request.user.avatar_url }}
          embed-description: ${{ github.event.pull_request.body }}
          embed-url: ${{ github.event.pull_request.html_url }}